In [6]:
import torch
import torch.nn as nn

# Sample Input
X = torch.randn(5)

# Custom Swish Activation
class Swish(nn.Module):

    def forward(self, x):
        return x * torch.sigmoid(x)

# Create Swish Layer
swish = Swish()

# Apply Swish
swish_output = swish(X)

# Compare with ReLU
relu = nn.ReLU()
relu_output = relu(X)

print("Input:")
print(X)

print("\nSwish Output:")
print(swish_output)

print("\nReLU Output:")
print(relu_output)


Input:
tensor([ 0.9829, -0.6744,  0.5512,  0.9420,  0.1361])

Swish Output:
tensor([ 0.7152, -0.2276,  0.3497,  0.6777,  0.0727])

ReLU Output:
tensor([0.9829, 0.0000, 0.5512, 0.9420, 0.1361])
